ALTER TABLE car DROP COLUMN name;
ALTER TABLE car ADD COLUMN model_name VARCHAR NOT NULL;
ALTER TABLE car DROP COLUMN engine_id;
ALTER TABLE car ADD COLUMN engine_type_id INTEGER NOT NULL REFERENCES engine_type(id);
ALTER TABLE car ADD COLUMN engine_volume_id INTEGER NOT NULL REFERENCES engine_volume(id);
ALTER TABLE car ADD COLUMN brand_id INTEGER NOT NULL REFERENCES brand(id);
ALTER TABLE car ADD COLUMN horsepower INTEGER NOT NULL;
ALTER TABLE car ADD COLUMN production_year INTEGER NOT NULL;